name: Local deployment to Kind
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:     
 deploy-linux:
   runs-on: [self-hosted, Linux, X64]
   steps:
     - uses: actions/checkout@v3
     - name: Helm deployment
       env:
         POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
       run: |
         helm upgrade postgresql bitnami/postgresql --version 12.1.9 -n cubix --set auth.password="$POSTGRESQL_PASSWORD" -f values.yaml --install
